/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package libcore/cmd/gobind */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 8 "go_libcoremain.go"

#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "libcore.h"


#line 1 "cgo-generated-wrapper"

#line 8 "go_main.go"

#include <stdlib.h>
#include <stdint.h>
#include "seq.h"
#include "universe.h"


#line 1 "cgo-generated-wrapper"

#line 11 "seq.go"


 #include <stdlib.h>
 #include "seq.h"

#line 1 "cgo-generated-wrapper"

#line 11 "seq_android.go"


#include <jni.h>
#include <stdint.h>
#include <stdlib.h>
#include "seq_android.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int32_t proxylibcore_BoxInstance_Close(int32_t refnum);
extern int32_t proxylibcore_BoxInstance_PreStart(int32_t refnum);
extern int64_t proxylibcore_BoxInstance_QueryStats(int32_t refnum, nstring param_tag, nstring param_direct);
extern char proxylibcore_BoxInstance_SelectOutbound(int32_t refnum, nstring param_tag);
extern void proxylibcore_BoxInstance_SetAsMain(int32_t refnum);
extern void proxylibcore_BoxInstance_SetV2rayStats(int32_t refnum, nstring param_outbounds);
extern void proxylibcore_BoxInstance_Sleep(int32_t refnum);
extern int32_t proxylibcore_BoxInstance_Start(int32_t refnum);
extern void proxylibcore_BoxInstance_Wake(int32_t refnum);
extern int32_t new_libcore_BoxInstance();
extern void proxylibcore_ExchangeContext_ErrnoCode(int32_t refnum, int32_t param_code);
extern void proxylibcore_ExchangeContext_ErrorCode(int32_t refnum, int32_t param_code);
extern void proxylibcore_ExchangeContext_OnCancel(int32_t refnum, int32_t param_callback);
extern void proxylibcore_ExchangeContext_RawSuccess(int32_t refnum, nbyteslice param_result);
extern void proxylibcore_ExchangeContext_Success(int32_t refnum, nstring param_result);
extern int32_t new_libcore_ExchangeContext();
extern void proxylibcore_StringBox_Value_Set(int32_t refnum, nstring v);
extern nstring proxylibcore_StringBox_Value_Get(int32_t refnum);
extern int32_t new_libcore_StringBox();
extern void proxylibcore_StunResult_Text_Set(int32_t refnum, nstring v);
extern nstring proxylibcore_StunResult_Text_Get(int32_t refnum);
extern void proxylibcore_StunResult_Success_Set(int32_t refnum, char v);
extern char proxylibcore_StunResult_Success_Get(int32_t refnum);
extern int32_t new_libcore_StunResult();
extern int32_t proxylibcore_BoxPlatformInterface_AutoDetectInterfaceControl(int32_t refnum, int32_t param_fd);

/* Return type for proxylibcore_BoxPlatformInterface_FindConnectionOwner */
struct proxylibcore_BoxPlatformInterface_FindConnectionOwner_return {
	int32_t r0;
	int32_t r1;
};
extern struct proxylibcore_BoxPlatformInterface_FindConnectionOwner_return proxylibcore_BoxPlatformInterface_FindConnectionOwner(int32_t refnum, int32_t param_ipProtocol, nstring param_sourceAddress, int32_t param_sourcePort, nstring param_destinationAddress, int32_t param_destinationPort);

/* Return type for proxylibcore_BoxPlatformInterface_OpenTun */
struct proxylibcore_BoxPlatformInterface_OpenTun_return {
	nint r0;
	int32_t r1;
};
extern struct proxylibcore_BoxPlatformInterface_OpenTun_return proxylibcore_BoxPlatformInterface_OpenTun(int32_t refnum, nstring param_singTunOptionsJson, nstring param_tunPlatformOptionsJson);

/* Return type for proxylibcore_BoxPlatformInterface_PackageNameByUid */
struct proxylibcore_BoxPlatformInterface_PackageNameByUid_return {
	nstring r0;
	int32_t r1;
};
extern struct proxylibcore_BoxPlatformInterface_PackageNameByUid_return proxylibcore_BoxPlatformInterface_PackageNameByUid(int32_t refnum, int32_t param_uid);

/* Return type for proxylibcore_BoxPlatformInterface_UIDByPackageName */
struct proxylibcore_BoxPlatformInterface_UIDByPackageName_return {
	int32_t r0;
	int32_t r1;
};
extern struct proxylibcore_BoxPlatformInterface_UIDByPackageName_return proxylibcore_BoxPlatformInterface_UIDByPackageName(int32_t refnum, nstring param_packageName);
extern char proxylibcore_BoxPlatformInterface_UseProcFS(int32_t refnum);
extern nstring proxylibcore_BoxPlatformInterface_WIFIState(int32_t refnum);
extern int32_t proxylibcore_Func_Invoke(int32_t refnum);
extern void proxylibcore_HTTPClient_Close(int32_t refnum);
extern void proxylibcore_HTTPClient_KeepAlive(int32_t refnum);
extern void proxylibcore_HTTPClient_ModernTLS(int32_t refnum);
extern int32_t proxylibcore_HTTPClient_NewRequest(int32_t refnum);
extern void proxylibcore_HTTPClient_PinnedSHA256(int32_t refnum, nstring param_sumHex);
extern void proxylibcore_HTTPClient_PinnedTLS12(int32_t refnum);
extern void proxylibcore_HTTPClient_RestrictedTLS(int32_t refnum);
extern void proxylibcore_HTTPClient_TryH3Direct(int32_t refnum);
extern void proxylibcore_HTTPClient_TrySocks5(int32_t refnum, int32_t param_port);
extern void proxylibcore_HTTPRequest_AllowInsecure(int32_t refnum);

/* Return type for proxylibcore_HTTPRequest_Execute */
struct proxylibcore_HTTPRequest_Execute_return {
	int32_t r0;
	int32_t r1;
};
extern struct proxylibcore_HTTPRequest_Execute_return proxylibcore_HTTPRequest_Execute(int32_t refnum);
extern void proxylibcore_HTTPRequest_SetContent(int32_t refnum, nbyteslice param_content);
extern void proxylibcore_HTTPRequest_SetContentString(int32_t refnum, nstring param_content);
extern void proxylibcore_HTTPRequest_SetHeader(int32_t refnum, nstring param_key, nstring param_value);
extern void proxylibcore_HTTPRequest_SetMethod(int32_t refnum, nstring param_method);
extern int32_t proxylibcore_HTTPRequest_SetURL(int32_t refnum, nstring param_link);
extern void proxylibcore_HTTPRequest_SetUserAgent(int32_t refnum, nstring param_userAgent);

/* Return type for proxylibcore_HTTPResponse_GetContent */
struct proxylibcore_HTTPResponse_GetContent_return {
	nbyteslice r0;
	int32_t r1;
};
extern struct proxylibcore_HTTPResponse_GetContent_return proxylibcore_HTTPResponse_GetContent(int32_t refnum);

/* Return type for proxylibcore_HTTPResponse_GetContentString */
struct proxylibcore_HTTPResponse_GetContentString_return {
	int32_t r0;
	int32_t r1;
};
extern struct proxylibcore_HTTPResponse_GetContentString_return proxylibcore_HTTPResponse_GetContentString(int32_t refnum);
extern int32_t proxylibcore_HTTPResponse_GetHeader(int32_t refnum, nstring param_p0);
extern int32_t proxylibcore_HTTPResponse_WriteTo(int32_t refnum, nstring param_path);
extern int32_t proxylibcore_LocalDNSTransport_Exchange(int32_t refnum, int32_t param_ctx, nbyteslice param_message);
extern int32_t proxylibcore_LocalDNSTransport_Lookup(int32_t refnum, int32_t param_ctx, nstring param_network, nstring param_domain);
extern int64_t proxylibcore_LocalDNSTransport_NetworkHandle(int32_t refnum);
extern char proxylibcore_LocalDNSTransport_Raw(int32_t refnum);
extern void proxylibcore_NB4AInterface_Selector_OnProxySelected(int32_t refnum, nstring param_selectorTag, nstring param_tag);
extern char proxylibcore_NB4AInterface_UseOfficialAssets(int32_t refnum);
extern void proxylibcore__ForceGc();
extern void proxylibcore__InitCore(nstring param_process, nstring param_cachePath, nstring param_internalAssets, nstring param_externalAssets, int32_t param_maxLogSizeKb, char param_logEnable, int32_t param_if1, int32_t param_if2, int32_t param_if3);
extern void proxylibcore__NekoLogClear();
extern void proxylibcore__NekoLogPrintln(nstring param_s);
extern int32_t proxylibcore__NewHttpClient();

/* Return type for proxylibcore__NewSingBoxInstance */
struct proxylibcore__NewSingBoxInstance_return {
	int32_t r0;
	int32_t r1;
};
extern struct proxylibcore__NewSingBoxInstance_return proxylibcore__NewSingBoxInstance(nstring param_config, int32_t param_localTransport);
extern void proxylibcore__ResetAllConnections(char param_system);
extern nbyteslice proxylibcore__Sha1(nbyteslice param_data);
extern nstring proxylibcore__Sha256Hex(nbyteslice param_data);
extern int32_t proxylibcore__StunTest(nstring param_server);
extern int32_t proxylibcore__Unxz(nstring param_archive, nstring param_path);
extern int32_t proxylibcore__Unzip(nstring param_archive, nstring param_path);

/* Return type for proxylibcore__UrlTest */
struct proxylibcore__UrlTest_return {
	int32_t r0;
	int32_t r1;
};
extern struct proxylibcore__UrlTest_return proxylibcore__UrlTest(int32_t param_i, nstring param_link, int32_t param_timeout);
extern nstring proxylibcore__VersionBox();
extern nstring proxy_error_Error(int32_t refnum);

// IncGoRef is called by foreign code to pin a Go object while its refnum is crossing
// the language barrier
extern void IncGoRef(int32_t refnum);

// DestroyRef is called by Java to inform Go it is done with a reference.
extern void DestroyRef(int32_t refnum);

#ifdef __cplusplus
}
#endif
